# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sumoverk <- function(G, rgky, aj, dj, betjy, gamjy, X) {
    .Call(`_vemirt_sumoverk`, G, rgky, aj, dj, betjy, gamjy, X)
}

ngest <- function(LiA, y, Nvec, G) {
    .Call(`_vemirt_ngest`, LiA, y, Nvec, G)
}

rgkest <- function(j, Xijk, LiA, y, Nvec, G, N, m) {
    .Call(`_vemirt_rgkest`, j, Xijk, LiA, y, Nvec, G, N, m)
}

eigenMapMatMult <- function(A, B) {
    .Call(`_vemirt_eigenMapMatMult`, A, B)
}

dmvnrm2 <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_vemirt_dmvnrm2`, x, mean, sigma, logd)
}

Estep1 <- function(resp, Nvec, X, y, G, yallgroup, Mulist, Siglist, gra, grd, grbeta, grgamma, r, J, m, N) {
    .Call(`_vemirt_Estep1`, resp, Nvec, X, y, G, yallgroup, Mulist, Siglist, gra, grd, grbeta, grgamma, r, J, m, N)
}

scocal <- function(j, ng, rgk, a, d, bet, gam, maxtol, X, yallgroup, y, G, r, m, eta) {
    .Call(`_vemirt_scocal`, j, ng, rgk, a, d, bet, gam, maxtol, X, yallgroup, y, G, r, m, eta)
}

soft2 <- function(s, tau) {
    .Call(`_vemirt_soft2`, s, tau)
}

Mstep <- function(j, ng, rgk, gra, grd, grbeta, grgamma, maxtol, X, yallgroup, y, G, r, m, eta) {
    .Call(`_vemirt_Mstep`, j, ng, rgk, gra, grd, grbeta, grgamma, maxtol, X, yallgroup, y, G, r, m, eta)
}

Mstepadapt <- function(j, ng, rgk, gra, grd, grbeta, grbeta00, grgamma, grgamma00, maxtol, X, yallgroup, y, G, r, m, eta, lam) {
    .Call(`_vemirt_Mstepadapt`, j, ng, rgk, gra, grd, grbeta, grbeta00, grgamma, grgamma00, maxtol, X, yallgroup, y, G, r, m, eta, lam)
}

ecfa2 <- function(u, Mu, Sigma, domain, person, item, eta, new_a, new_b) {
    .Call(`_vemirt_ecfa2`, u, Mu, Sigma, domain, person, item, eta, new_a, new_b)
}

